export const url = "https://www.clubcrackers.com/en_US/home.html";
export const ourFood = "Our Food";
export const homePageImage = [
    "#tns1-item1 > .content_wrapper",
    "#tns1-item2 > .content_wrapper",
    "#tns1-item3 > .content_wrapper"
];
export const nextButton = 'Carousel Next Slide'
export const homePageCard = [
    {
        name: "Club® Original Crackers Image",
        img: "Club® Original Crackers",
        des: "Flaky and buttery with a hint"
    },
    {
        name: "Club® Sweet Hawaiian Crackers",
        img: "Club® Sweet Hawaiian Cracker",
        des: "Inspired by Sweet Hawaiian"
    },
    {
        name: "Club® Multi-Grain Crackers",
        img: "Club® Multi-Grain Crackers",
        des: "Buttery and flaky, with a"
    },
    {
        name: "Club® Reduced Fat Crackers",
        img: "Club® Reduced Fat Crackers",
        des: "Enjoy the buttery melt-in-"
    },
    {
        name: "Club® Minis Original Crackers",
        img: "Club® Minis Original Crackers",
        des: "The buttery melt-in-your-"
    },
    {
        name: "Club® Minis Parmesan Garlic",
        img: "Club® Minis Parmesan Garlic",
        des: "Savor the light, flaky"
    },
    {
        name: "Club® Snack Stacks™ Image",
        img: "Club® Snack Stacks™",
        des: "Snack Stacks™ are the perfect"
    },
    {
        name: 'Club® Snack Stacks™ Stacks',
        img: 'Club® Snack Stacks™ Stacks',
        des: "Savor light, flaky, buttery"
    }
]
export const expectedCardImg = ["",];
export const contactUsText = "Contact Us";


export const recipeNames = [
    {
        name: "Sweet and Spicy Bacon Crackers",
        img: "Sweet and Spicy Bacon Crackers",
        hed: "Sweet and Spicy Bacon Crackers",
        firstTime: "10",
        secondTime: "35",
        recipeTexts: [
            'Bacon and Club® Crackers',
            'Prep Time (min):',
            'Servings 6-',
            '-8',
            'Ingredients 1 sleeve Club®',
            '1. Preheat oven to 350°F.',
            '2. Place crackers in single',
            '3. Bake until bacon is crisp',
            'This recipe uses: Club®'
        ],
    },
    {
        name: 'Pepperoni Pizza Snack Mix',
        img: 'Pepperoni Pizza Snack Mix',
        hed: "Club® Crackers Pepperoni",

        recipeTexts: [
            "A fun twist on Pizza, wit",
            "Prep Time (min):",
            'Total Time (min):',
            'Servings Varies',
            'Mix Club® Minis Original',
            'Directions Mix Club® Minis',
            'A fun twist on Pizza, with',
        ]
    },
    {
        name: 'Sweet & Salty Snack Mix Sweet',
        img: 'Club® Crackers Sweet & Salty',
        hed: 'Club® Crackers Sweet & Salty',
        firstTime: "",
        secondTime: "",
        recipeTexts: [
            'Dazzle your family with this',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings Varies',
            'Ingredients Club® Minis',
            'Directions Mix Club® Minis',
            'Mix Club® Minis Original',
            'This recipe uses: Club® Minis',
        ]
    },
    {
        name: 'Whipped Basil Dip with',
        img: 'Whipped Basil Dip with',
        hed: 'Whipped Basil Dip with',
        firstTime: '8',
        recipeTexts: [
            'Basil and tomatoes combine',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '5',
            '21',
            'Ingredients 1 tablespoon',
            '1 tablespoon olive oil, plus',
            'pint cherry tomatoes',
            '1 cup (8 oz) feta cheese',
            '1 cup (8 oz) cream cheese,',
            '1/2 cup basil leaves, tightly',
            'clove garlic',
            '/2 teaspoon salt',
            '1/4 teaspoon finely ground',
            '1. Heat oil in a large',
            '2. Combine feta, cream cheese',
            '3. Top with blistered',
            'This recipe uses: Club®',
            'Directions 1. Heat oil in a',
        ]
    },
    {
        name: 'Apple-and-Cheddar Topped',
        img: 'Apple-and-Cheddar Topped',
        hed: 'Apple-and-Cheddar Topped',
        recipeTexts: [
            'The crunch of toasted pecans',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '22',
            'Ingredients 8 ounces extra',
            'ounces extra sharp cheddar cheese',
            '44 Club® Multi-Grain Crackers',
            '44 Town House® Original',
            '1 medium apple, cored and',
            '44 pecan halves, toasted',
            '/4 cup honey',
            '1. Cut cheese into 44',
            '2. Top each with a pecan half',
            'Note: To prevent browning,',
            'Directions 1. Cut cheese into',
            'This recipe uses: Club® Multi',
        ]

    },
    {
        name: 'Easy Sausage and Cheese',
        img: 'Easy Sausage and Cheese',
        hed: 'Easy Sausage and Cheese',
        recipeTexts: [
            'Pair your favorite cheeses',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '12',
            'Prep Time (min): 15 Total',
            'Ingredients 8 ounces',
            'Hillshire Farm® Summer',
            'sharp cheddar cheese, Swiss',
            'seedless red grapes, seedless',
            '32 Town House® Original',
            '32 Club® Original crackers',
            '1/2 cup drained gherkin',
            '/2 cup drained, pitted ripe olives',
            '1/4 cup seed-style mustard or',
            '1. Cut summer sausage and',
            'Directions 1. Cut summer',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Mediterranean Tuna Salad',
        img: 'Mediterranean Tuna Salad',
        hed: 'Mediterranean Tuna Salad',
        firstTime: '',
        recipeTexts: [
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '16',
            'Prep Time (min): 10 Total',
            'Directions 1. In small bowl',
            '1. In small bowl whisk',
            'tablespoon olive oil',
            'tablespoon red wine vinegar',
            '1/2 teaspoon dried oregano',
            'clove garlic, minced',
            'Dash salt',
            '1 can (6 1/2 oz.) chunk white',
            '/2 cup finely chopped carrot',
            '1/4 cup finely chopped red',
            'tablespoons chopped fresh parsley',
            'Ingredients 1 tablespoon',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Cranberry-Cilantro Salsa with',
        img: 'Cranberry-Cilantro Salsa with',
        hed: 'Cranberry-Cilantro Salsa with',
        recipeTexts: [
            'Shimmering cranberry salsa',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            'Prep Time (min): 20 Total',
            'Ingredients 1 bag (12 oz.)',
            'bag (12 oz.) fresh cranberries',
            '/3 cup sugar',
            'large jalapeño pepper, seeded',
            'tablespoons lime juice',
            '/2 teaspoon ground ginger',
            '/3 cup chopped fresh cilantro',
            'ounces cream cheese, softened',
            '/3 cup sliced green onions',
            '1. In food processor combine',
            '2. Stir together cream cheese',
            'Directions 1. In food',
            'Ingredients 1 bag (12 oz.)',
            'This recipe uses: Club®',
        ]

    },

    {
        name: 'Sweet & Salty 7-Layer Dip',
        img: 'Sweet & Salty 7-Layer Dip',
        hed: 'Sweet & Salty 7-Layer Dip',
        recipeTexts: [
            'This scrumptious dip,',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            'Prep Time (min): 5 Total Time',
            'Directions 1. In 9-inch pie',
            '1. In 9-inch pie plate spread',
            'Ingredients 1 cup Jif® Whips',
            '1 cup Jif® Whips Whipped',
            '/2 cup crushed pretzels',
            '1/4 cup salted caramel ice',
            '2 cups frozen non-dairy',
            '1/2 cup sweetened flaked',
            '1/2 cup miniature semi-sweet',
            '/4 cup chopped peanuts',
            'This recipe uses: Club®',
        ]

    },

    {
        name: 'Chocolate Peanut Butter',
        img: 'Chocolate Peanut Butter',
        hed: 'Chocolate Peanut Butter',
        recipeTexts: [
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            'Prep Time (min): 30 Total',
            'Ingredients 2 cups semi-sweet',
            'cups semi-sweet chocolate morsels',
            '48 Club® Original Crackers',
            '/4 cup English toffee bits',
            '1 1/4 cups Jif® Whips Whipped',
            '1. Line baking sheet with wax',
            '2. Dip each Club® Original',
            '3. Spread about 2 teaspoons',
            'Directions 1. Line baking',
            'Ingredients 2 cups semi-sweet',
            'This recipe uses: Club®',
        ]

    },
    {
        name: "Cheddar, Bacon and Spinach",
        img: 'Cheddar, Bacon and Spinach',
        hed: 'Cheddar, Bacon and Spinach',
        recipeTexts: [
            'A familiar spinach dip',
            'Prep Time (min):',
            'Total Time (min):',
            'Prep Time (min): 20 Total',
            '2. Let stand at room',
            'Ingredients 1 1/2 cups fat',
            'fat free plain Greek yogurt',
            '1 1/2 cups (6 oz.) shredded',
            '1 package (10 oz.) frozen',
            '1/3 cup seeded and finely',
            '1/4 cup slivered almonds,',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Cheddar and Tomato-Jam Canapés',
        img: 'Cheddar and Tomato-Jam Canapés',
        hed: 'Cheddar and Tomato-Jam Canapés',
        firstTime: '20',
        recipeTexts: [
            'A ginger-and-cinnamon-spiced',
            'Prep Time (min): 20 Total',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '40',
            '16',
            'Directions 1. In medium',
            '1 can (14.5 oz.) chili-style',
            'tablespoon cider vinegar',
            '1 tablespoon grated fresh',
            '/2 teaspoon cinnamon',
            '8 ounces sharp Cheddar cheese',
            '64 Club® Original crackers',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Cream Cheese with Pepper',
        img: 'Cream Cheese with Pepper Jelly',
        hed: 'Cream Cheese with Pepper Jelly',
        firstTime: '8',
        recipeTexts: [
            '/4 cup jalapeño pepper jelly',
            'package (8oz.) cream cheese',
            '1 Tablespoon broken pecans,',
            'Ingredients 1/4 cup jalapeño',
            'Directions 1. In small',
            '1. In small microwave-safe',
            '2. Place cream cheese on',
            'Microwave cooking times may',
            'Yield: 1 cup spread; 8',
            'This recipe uses: Club®',
        ]
    },

    {
        name: 'Creamy Bacon and Cheese Dip',
        img: 'Creamy Bacon and Cheese Dip',
        hed: 'Creamy Bacon and Cheese Dip',
        firstTime: '40',
        secondTime: '30',
        recipeTexts: [
            'Total Time (min):',
            'Servings',
            'Prep Time (min): 15 Total',
            '15',
            'Directions 1. In medium bowl',
            '1. In medium bowl stir',
            '2. Spread in 2-quart baking',
            '3. Serve with Club® Original',
            'tub (16 oz.) sour cream',
            '1 package (8 oz.) cream',
            '2 cups (8 oz.) shredded',
            'cup chopped green onions',
            'jar (3 oz.) bacon bits',
            'envelope (1 oz.) onion soup mix',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Fruit and Cheese Cracker',
        img: 'Fruit and Cheese Cracker',
        hed: 'Fruit and Cheese Cracker',
        recipeTexts: [
            'Stack your favorite fruits',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings Varies',
            'Varies',
            'Prep Time (min): 5 Total Time',
            'Directions 1. Thinly slice',
            '1. Thinly slice cheeses. Top',
            'Ingredients Cheddar cheese',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Slow Cooker Cheeseburger Dip',
        img: 'Slow Cooker Cheeseburger Dip',
        hed: 'Slow Cooker Cheeseburger Dip',
        recipeTexts: [
            'Hearty pub food, like this',
            'Total Time (min):',
            'Servings',
            'Prep Time (min): 15 Total',
            '1. In skillet cook ground',
            '2. In 1 1/2- to 2-quart slow',
            '3. Stir and serve immediately',
            'pound lean ground beef',
            '/2 cup chopped onion',
            'clove garlic, minced',
            '1 pound American cheese',
            '/2 cup evaporated fat-free milk',
            '/4 cup ketchup',
            'tablespoons dill pickle relish',
            '2 tablespoons spicy brown',
            '1/4 cup finely chopped and',
            'Ingredients 1 pound lean',
            'Directions 1. In skillet cook',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Easy Sausage and Cheese',
        img: 'Easy Sausage and Cheese',
        hed: 'Easy Sausage and Cheese',
        recipeTexts: [
            'Pair your favorite cheeses',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '12',
            'Prep Time (min): 15 Total',
            'Directions 1. Cut summer',
            '1. Cut summer sausage and',
            'Ingredients 8 ounces',
            '8 ounces Hillshire Farm®',
            'sharp cheddar cheese, Swiss',
            '8 ounces seedless red grapes',
            '32 Club® Original crackers',
            '1/2 cup drained gherkin',
            '/2 cup drained, pitted ripe olives',
            '1/4 cup seed-style mustard or',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Cranberry-Cilantro Salsa with',
        img: 'Cranberry-Cilantro Salsa with',
        hed: 'Cranberry-Cilantro Salsa with',
        recipeTexts: [
            'Shimmering cranberry salsa',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            'Prep Time (min): 20 Total',
            '1. In food processor combine',
            '2. Stir together cream cheese',
            'Directions 1. In food',
            'Ingredients 1 bag (12 oz.)',
            'bag (12 oz.) fresh cranberries',
            '/3 cup sugar',
            'large jalapeño pepper, seeded',
            'tablespoons lime juice',
            '/2 teaspoon ground ginger',
            '/3 cup chopped fresh cilantro',
            'ounces cream cheese, softened',
            '/3 cup sliced green onions',
        ]

    },
    {
        name: 'Warm Apple Pie Dip Warm Apple',
        img: 'Warm Apple Pie Dip',
        hed: 'Warm Apple Pie Dip',
        recipeTexts: [
            'Dip a Club® cracker into this',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings 6-',
            'Prep Time (min): 10 Total',
            'Directions 1. Preheat oven to',
            '1. Preheat oven to 350°F.',
            '2. Spread mixture evenly over',
            '3. Combine apples, remaining',
            '4. Cook, stirring',
            '5. Bake until dip is warm and',
            'Tip: Easily substitute',
            'Ingredients 2 cups (16 oz)',
            'cups (16 oz) cream cheese, softened',
            '/4 cup brown sugar, divided',
            '1 1/2 teaspoons ground',
            '/4 teaspoon ground nutmeg, divided',
            '2 medium Granny Smith apples',
            '1/2 cup chopped pecans,',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Pear and Blue Cheese Crackers',
        img: 'Pear and Blue Cheese Crackers',
        hed: 'Pear and Blue Cheese Crackers',
        recipeTexts: [
            'Pungent blue cheese perfectly',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '6',
            'Prep Time (min): 10 Total',
            '1. Trim pear slices to fit on',
            'Note: To prevent browning,',
            '/4 cup crumbled blue cheese (1 oz.)',
            '18 Club® Reduced Fat crackers',
            '1 small red or green pear,',
            'Ingredients 1 small red or',
            'Directions 1. Trim pear',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Chopped Veggie Salad on Club',
        img: 'Chopped Veggie Salad on Club',
        hed: 'Chopped Veggie Salad on Club',
        recipeTexts: [
            'These easy appetizers,',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            'Prep Time (min): 10 Total',
            '1. In medium bowl stir',
            '2. Spread hummus on Club®',
            '1/2 cup finely chopped yellow',
            '/2 cup very finely chopped and seeded tomato',
            '4 teaspoons fat free Italian',
            '/3 cup garlic hummus',
            '24 Club® Reduced Fat Crackers',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Egg Salad with Fresh Herbs',
        img: 'Egg Salad with Fresh Herbs',
        hed: 'Egg Salad with Fresh Herbs',
        firstTime: '135',
        recipeTexts: [
            'Comforting, old-fashioned egg',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '15',
            '135',
            'Prep Time (min): 15 Total',
            '9 hard-cooked eggs, peeled',
            '/4 cup finely chopped celery',
            '/4 cup sliced green onions',
            '2 tablespoons finely chopped',
            '1 tablespoon chopped fresh',
            '1/2 cup reduced-fat',
            '2 tablespoons spicy brown',
            '/4 teaspoon salt',
            '/4 teaspoon pepper',
            '1. Cut eggs into 1/2-inch',
            '2. In small bowl whisk',
            '3. Stir egg salad. Serve on',
            'Directions 1. Cut eggs into 1',
            'Ingredients 9 hard-cooked',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Warm Sausage and Spinach Dip',
        img: 'Warm Sausage and Spinach Dip',
        hed: 'Warm Sausage and Spinach Dip',
        firstTime: '20',
        secondTime: '24',
        recipeTexts: [
            'Banana pepper rings add just',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '35',
            'Directions 1. In large',
            '1. In large nonstick skillet',
            '2. In same skillet cook onion',
            '3. In food processor bowl',
            '4. Spoon into shallow 1-quart',
            '12 ounces refrigerated',
            '/2 cup finely chopped onion',
            '1 package (8 oz.) reduced-fat',
            '3/4 cup finely shredded',
            '/4 cup mayonnaise',
            '1/4 cup fat-free plain Greek',
            'clove garlic, peeled',
            'cup chopped fresh spinach',
            '1/3 cup seeded and finely',
            '2 tablespoons hot banana',
            'This recipe uses: Club®',

        ]

    },
    {
        name: 'Fruit and Almond Tart Fruit',
        img: 'Fruit and Almond Tart',
        hed: 'Fruit and Almond Tart',
        firstTime: '12',
        recipeTexts: [
            'Everything you want in a',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '95',
            '25',
            '1/2 cups Club® Multi-Grain crackers',
            '/4 cup granulated sugar',
            'teaspoon cinnamon',
            '/4 cup butter or margarine, melted',
            '12 ounces reduced-fat cream',
            '/3 cup firmly packed brown sugar',
            '/4 cup fat-free milk',
            '/4 teaspoon almond extract',
            '1/2 cup finely chopped',
            '3 cups halved fresh',
            '1/4 cup red currant jelly,',
            '2. In small mixing bowl beat',
            '3. Top with fruit. Drizzle',
            '*Note: Soften in microwave at',
            '**Note: To toast nuts, spread',
            '***Note: If desired,',
            'Directions 1. In medium bowl',
            'Ingredients 1 1/2 cups Club®',
            'This recipe uses: Club® Multi',
        ]

    },
    {
        name: 'Sour Cream Dip Sour Cream Dip',
        img: 'Sour Cream Dip',
        hed: 'Sour Cream Dip',
        recipeTexts: [
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '16',
            'Prep Time (min): 5 Total Time',
            '1. In small bowl combine sour',
            'cup sour cream',
            'cup mayonnaise',
            'tablespoons chopped fresh parsley',
            'teaspoon dried dill weed',
            '/4 teaspoon celery salt',
            '/4 teaspoon onion powder',
            '/8 teaspoon garlic powder',
            'Ingredients 1 cup sour cream',
            'Directions 1. In small bowl',
            'This recipe uses: Club® Original Crackers WHERE TO BUY Where to Buy',
            'This recipe uses: Club® Multi',
        ]

    },
    {
        name: 'Easy Sausage and Cheese',
        img: 'Easy Sausage and Cheese',
        hed: 'Easy Sausage and Cheese',
        recipeTexts: [
            'Pair your favorite cheeses',
            'Prep Time (min):',
            'Servings',
            'Prep Time (min): 15 Total',
            'Hillshire Farm® Summer',
            '8 ounces sharp cheddar cheese',
            '8 ounces seedless red grapes',
            '32 Town House® Original',
            '32 Club® Original crackers',
            '1/2 cup drained gherkin',
            '/2 cup drained, pitted ripe olives',
            '1/4 cup seed-style mustard or',
            '1. Cut summer sausage and',
            'Directions 1. Cut summer',
            'This recipe uses: Club®',
        ]

    },
    {
        name: 'Baked Cheese-and-Chili Pepper',
        img: 'Baked Cheese-and-Chili Pepper',
        hed: 'Baked Cheese-and-Chili Pepper',
        recipeNames: [
            'Spicy chili peppers and',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            'Prep Time (min): 15 Total',
            '1. In food processor bowl',
            '2. Transfer mixture to bowl.',
            '3. Bake at 350°F for 15 to 20',
            'Directions 1. In food',
            '4 ounces reduced-fat cream',
            '/2 cup mayonnaise',
            '1 can (4 oz.) chopped green',
            '2 tablespoons finely chopped',
            '/8 teaspoon garlic powder',
            '2 cups (8 oz.) shredded extra',
            '1 cup (4 oz.) shredded',
            '3/4 cup frozen fire-roasted',
            '1/2 cup seeded and chopped',
            '/4 cup sliced green onions',
            'Ingredients 4 ounces reduced-',
            'This recipe uses: Club®',
        ]
    },
    {
        name: 'Spicy Red Zone Meatballs',
        img: 'Spicy Red Zone Meatballs',
        hed: 'Spicy Red Zone Meatballs',
        firstTime: '2 tablespoons ketchup',
        secondTime: '1/2 cup ketchup',
        recipeNames: [
            'Pickle relish and tomato',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings 16',
            '1 egg, slightly beaten',
            '24 Club® Original Crackers',
            'tablespoon mustard',
            'pound lean ground beef',
            'can (15 oz) tomato sauce',
            '/4 cup firmly packed brown sugar',
            '/4 cup finely chopped onion',
            '2 tablespoons sweet pickle',
            'tablespoon Worcestershire sauce',
            'tablespoons vinegar',
            '/4 teaspoon pepper',
            '1 can (20 oz) pineapple',
            '1. In a large bowl combine',
            '2. Bake at 400° F for 10',
            '3. In large saucepan combine',
            '4. Stir meatballs and',
            'Note: for 32 servings, double',
            'This recipe uses: Club®',
        ]
    },
    {
        name: 'Roasted Red Pepper Dip',
        img: 'Roasted Red Pepper Dip',
        hed: 'Roasted Red Pepper Dip',
        recipeNames: [
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '1 package (8 oz.) cream',
            'clove garlic, peeled',
            '/2 cup chopped red bell pepper',
            'chopped fresh basil or 2',
            '1. In food processor bowl',
            '2. Stir in red pepper, green',
            '*NOTE: Soften cream cheese in',
            'Directions 1. In food',
            'This recipe uses: Club®',
        ]
    },
    {
        name: 'The Classic Snack The Classic',
        img: 'Club® Crackers Classic Snack',
        hed: 'Club® Crackers Classic Snack',
        recipeNames: [
            'These delicious Club®',
            'Total Time (min):',
            'Servings Varies',
            'Ingredients Club® Original',
            'Top Club® Original Crackers',
            'Directions Top Club® Original',
            'This recipe uses: Club®',
        ]
    },
    {
        name: 'Tomato Pesto Bites Tomato',
        img: 'Tomato Pesto Bites',
        hed: 'Tomato Pesto Bites',
        recipeNames: [
            '15',
            'Embrace simple, Mediterranean',
            'Total Time (min):',
            'Servings',
            '30',
            'Prep Time (min): 15 Total',
            'Ingredients 3/4 cup prepared',
            '/4 cup prepared basil pesto',
            '48 Club® Original crackers',
            '48 Club® Multi-Grain crackers',
            '3/4 cup tablespoon sliced,',
            'Drain any excess oil from pesto.',
            '2. Spread pesto on Club®',
            'Top with tomato slices and olives.',
            'Directions 1. Drain any',
            'This recipe uses: Club® Original Crackers WHERE TO BUY Where to Buy',
            'This recipe uses: Club® Multi',
        ]
    },
    {
        name: 'Lunchtime Favorite Lunchtime',
        img: 'Lunchtime Favorite',
        hed: 'Lunchtime Favorite',
        firstTime: 'Dijon mustard',
        secondTime: 'Shredded lettuce',
        recipeNames: [
            'Crackers topped with deli ham',
            'Total Time (min):',
            'Servings Varies',
            'Varies',
            'Servings Varies',
            '1. Top Club® Multi-Grain',
            'Thinly sliced deli ham',
            'Sliced Swiss cheese',
            'This recipe uses: Club® Multi',
        ]
    },
    {
        name: 'Stuffed Acorn Squash Stuffed',
        img: 'Stuffed Acorn Squash',
        hed: 'Stuffed Acorn Squash',
        recipeNames: [
            'Take advantage of fall',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            'medium acorn squash',
            '/2 cup finely chopped onion',
            '1/4 cup finely chopped green',
            '2 tablespoons margarine or',
            'teaspoons all-purpose flour',
            'cup milk',
            'cups Club® Original Crackers',
            'cup finely chopped ham',
            '/2 teaspoon dry mustard',
            '/4 teaspoon hot pepper sauce',
            'medium acorn squash',
            '/2 cup finely chopped onion',
            '1/4 cup finely chopped green',
            '2 tablespoons margarine or',
            'teaspoons all-purpose flour',
            'cup milk',
            'cups Club® Original Crackers',
            'cup finely chopped ham',
            '/2 teaspoon dry mustard',
            '/4 teaspoon hot pepper sauce',
            'Ingredients 2 medium acorn',
            '1. Lengthwise cut squash in',
            '2. Meanwhile, in medium',
            '3. Turn squash halves, cut',
        ]
    },
    {
        name: 'Ham and Swiss Quiche Ham and',
        img: 'Ham and Swiss Quiche',
        hed: 'Ham and Swiss Quiche',
        firstTime: '8',
        recipeNames: [
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '55',
            '1/2 cup Club® Multi-Grain',
            '/3 cup all-purpose flour',
            '/4 teaspoon pepper',
            '/8 teaspoon nutmeg',
            'cup low-fat cottage cheese',
            'cup shredded Swiss cheese',
            '/2 cup shredded carrots',
            '/4 cup sliced green onions',
            '1. Sprinkle Club® Multi-Grain',
            '2. In medium bowl whisk',
            '3. Bake at 350°F about 40',
            'Ingredients 1/2 cup Club®',
        ]
    },
    {
        name: 'Cinnamon-Sweet Potato Dip',
        img: 'Cinnamon-Sweet Potato Dip',
        hed: 'Cinnamon-Sweet Potato Dip',
        recipeNames: [
            'Sweet potato adds color,',
            'Servings',
            'medium (about 10 oz.) sweet potato',
            '/4 cup fat-free plain Greek yogurt',
            'tablespoon olive oil',
            '/2 teaspoon ground cinnamon',
            '/4 teaspoon ground ginger',
            'Ingredients 1 medium (about',
            '1. Scrub potato. Use fork to',
            '2. Halve potato. Scoop out',
            'Directions 1. Scrub potato.',
        ]
    },
    {
        name: 'South of the Border South of',
        img: 'South of the Border',
        hed: 'South of the Border',
        recipeNames: [
            'Prep Time (min):',
            'Total Time (min):',
            'Servings',
            '1. In small mixing bowl beat',
            '2. Spread salsa over cheese',
            '*NOTE: Soften cream cheese in',
            'cups shredded Cheddar cheese',
            '(8 oz.) cream cheese,',
            '1 can (4 oz.) chopped green',
            '1 jar (2 1/4 oz.) dried beef',
            '/4 cup salsa',
            'tablespoons chopped fresh parsley',
            'Directions 1. In small mixing',
            'Ingredients 2 cups shredded',
            'This recipe uses: Club® Original Crackers WHERE TO BUY Where to Buy',
            'This recipe uses: Club® Multi',
        ]
    },
    {
        name: 'Sour Cream Dip Sour Cream Dip',
        img: 'Sour Cream Dip Sour Cream Dip',
        hed: 'Sour Cream Dip Sour Cream Dip',
        recipeNames: [
            '1. In small bowl combine sour',
            'Directions 1. In small bowl',
            'Ingredients 1 cup sour cream',
            'This recipe uses: Club® Multi',
            'Next',
            'For your next party, skip the',
            'Directions 1. Place cheddar',
        ]
    },
    {
        name: 'Sweet & Salty Snack Mix Sweet',
        img: 'Club® Crackers Sweet & Salty',
        hed: 'Club® Crackers Sweet & Salty',
        recipeNames: [
            'Dazzle your family with this',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings Varies',
            'Varies',
            'Mix Club® Minis Original',
            'This recipe uses: Club® Minis',
        ]
    },
    {
        name: 'Club® Crackers Pepperoni',
        img: 'Club® Crackers Pepperoni',
        hed: 'Club® Crackers Pepperoni',
        recipeNames: [
            'A fun twist on Pizza, with',
            'Prep Time (min):',
            'Servings Varies',
            'Varies',
            'Ingredients Club® Minis',
            'Mix Club® Minis Original',
            'Directions Mix Club® Minis',
            'This recipe uses: Club® Minis',
        ]
    },
    {
        name: 'Club® FireCRACKER Mix Club®',
        img: 'Club® FireCRACKER Mix',
        hed: 'Club® FireCRACKER Mix',
        firstTime: '5',
        secondTime: '25',
        recipeNames: [
            '/3 cup unsalted butter, melted',
            'packet dry ranch dressing mix',
            'tablespoon red pepper flakes',
            'tablespoon garlic powder',
            '/2 tablespoon dried parsley',
            '/2 tablespoon dried oregano',
            '1. Preheat oven to 250°F.',
            '2. In separate large bowl,',
            '3. Transfer crackers to',
            '4. Bake, stirring',
            'Ingredients Club® Minis',
            'Directions 1. Preheat oven to',
            'This recipe uses: Club® Minis',
        ]
    },
    {
        name: 'Snowy Snack Mix Snowy Snack',
        img: 'Snowy Snack Mix Snowy Snack',
        hed: 'Snowy Snack Mix',
        recipeNames: [
            'A mix of your favorite snacks',
            'Prep Time (min):',
            'Total Time (min):',
            'Servings 6-',
            '-8',
            '10',
            'box Club® Mini Crackers',
            'cups popped popcorn',
            'cups miniature pretzels',
            '1 1/2 cups (12 oz) miniature',
            '2 cups (16 oz) white',
            '1 cup (8 oz) green and red',
            '3 cups powdered sugar, for',
            '1. Combine Club® Mini',
            '2. Heat white chocolate chips',
            '3. Before chocolate is fully',
            '4. Place powdered sugar in a',
            'Directions 1. Combine Club®',
            'Ingredients 1 box Club® Mini',
            'This recipe uses: Club® Minis',
        ]
    },

    {
        name: 'Asian Chicken Salad',
        img: 'Asian Chicken Salad',
        hed: 'Asian Chicken Salad',
        recipeNames: [
            'Prep Time (min):',
            'Servings',
            'tablespoons mayonnaise',
            '2 teaspoons reduced-sodium',
            '2 cups finely chopped, cooked',
            '1/2 cup finely chopped red',
            '1. In small bowl stir',
            '2. In medium bowl toss',
            'This recipe uses: Club®',
            'Directions 1. In small bowl',
            'Ingredients 2 tablespoons',
            'Prep Time (min):',
        ]
    }


]