export const url = 'https://basiscloudsolutionspvtltd--demoasset.sandbox.my.salesforce.com/?ec=301&startURL=%2Fvisualforce%2Fsession%3Furl%3Dhttps%253A%252F%252Fbasiscloudsolutionspvtltd--demoasset.sandbox.my.salesforce-setup.com%252Flightning%252Fsetup%252FObjectManager%252Fhome';
export const username = 'vijayakumarp@basiscloudsolutions.com.demoasset';
export const password = 'Basiscloud@1234';
export const firstName = 'Ravindra';
export const lastName = 'Bharathi';
export const salutation = 'Mr.';
export const email = 'ravindrabharathia01@gmail.com';
export const phone = '+919876543210';
export const company = 'BCS';
export const products = ["Alum Crystals", "Alpha Olefin Sulfonate"];
export const Quantitys = ["200 G", "500 G"];
export const leadStatus = 'Qualified';