// export const url = 'https://test.salesforce.com/';
// export const username = '$username';
// export const password = '$password';
// export const firstName = '$firstname';
// export const lastName = '$lastname';
// export const email = '$email';
// export const phone = '$phone';
// export const salutation = '$salutation';
// export const company = '$company';
// export const product = '$product';
// const temp = $TextfeildData
// const temp1 = $mobileNumber
// export const obj = JSON.parse(JSON.stringify(temp));
// export const obj1 = JSON.parse(JSON.stringify(temp1));

export const url = 'https://test.salesforce.com/';
export const username = 'vijayakumarp@basiscloudsolutions.com.floating';
export const password = 'Basiscloud@1234';
export const firstName = 'sibi';
export const lastName = 's';
export const email = 'sibis02@gmail.com';
export const phone = '+919876543210';
export const salutation = 'Mr.';
export const company = 'BCS';
export const product = 'Carpets';