export const url = 'https://test.salesforce.com/';
// export const username = '$username';
// export const password = '$password';
// export const firstName = '$firstname';
// export const lastName = '$lastname';
// export const email = '$email';
// export const phone = '$phone';
// export const salutation = '$salutation';
// export const company = '$company';
// export const product = '$product';
// export const stage = '$stage';
// export const products = '$products';
// export const quantity = '$quantity';

export const username = 'vijayakumarp@basiscloudsolutions.com.floating';
export const password = 'Basiscloud@1234';
export const firstName = 'sibi';
export const lastName = 's';
export const email = 'sibis02@gmail.com';
